import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

const translations = {
  en: {
    // Navigation
    home: "Home",
    modules: "Modules",
    progress: "My Journey",
    dailyCheckIn: "Daily Check-in",
    
    // Home
    welcomeTitle: "Driving Licence for Life",
    welcomeSubtitle: "For Your Fulfilled Life",
    welcomeSubtitle2: "Without Compromise",
    welcomeDescription: "Discover five key modules that will guide you on the path to an authentic, fulfilled, and happy life. Remember who you truly are.",
    startJourney: "Start Your Journey",
    exploreModules: "Explore Modules",
    continueJourney: "Continue Your Journey",
    todayEnergy: "Today's Energy",
    statsModules: "Modules",
    statsExercises: "Exercises",
    courseDescription: "5 Transformational Modules",
    courseSubDescription: "Your Path to a Fulfilled Life",
    courseDetailText: "Each module guides you through key areas of personal growth. Progress at your own pace and discover your potential.",
    
    // Energy Check-in
    howAreYou: "How is your energy today?",
    energyLevel: "Energy Level",
    yourMood: "Your Mood",
    radiant: "Radiant",
    positive: "Positive",
    neutral: "Neutral",
    low: "Low",
    struggling: "Struggling",
    addNote: "Add a reflection...",
    saveCheckIn: "Save Check-in",
    checkInSaved: "Check-in saved!",
    
    // Modules
    module: "Module",
    modulesTitle: "5 Transformational Modules",
    moduleSubtitle: "Your Path to a Fulfilled Life. Each module guides you through key areas of personal growth.",
    locked: "Complete previous module first",
    lessons: "Lessons",
    completed: "Completed",
    startModule: "Begin Module",
    continueModule: "Continue",
    
    // Module 1
    m1Title: "Identity",
    m1Subtitle: "Remember Who You Truly Are",
    m1Description: "Forget what you have learned. Remember who you truly are. Decide what you want to believe. Set your own standards. And act on them.",
    m1L1Title: "Forget What You Learned",
    m1L1Content: "Most of what we believe about ourselves was given to us by others — parents, teachers, society. These beliefs shaped us, but they are not us. Today, we begin by letting go of borrowed identities.",
    m1L1Exercise: "Write down 3 beliefs about yourself that you received from others. For each one, ask: 'Is this truly mine? Does this serve my highest self?'",
    m1L2Title: "Remember Who You Truly Are",
    m1L2Content: "YOUR IDENTITY — who you think you are — determines how you behave every day, how you think, how you dress, how you care for yourself, how you speak, how you walk, who you associate with. And it also determines how others treat you and see you. Who are you? Are you a beggar, a poor thing, a little girl, a little boy — or a queen, a king? Beneath all the layers of conditioning lies your true essence — pure energy, pure potential, pure love. You are not your job, your past, or your mistakes. You are consciousness experiencing life.",
    m1L2Exercise: "Close your eyes for 5 minutes. Breathe deeply. Ask yourself: 'Who am I without my story?' Write what comes to you.",
    m1L3Title: "Decide What to Believe",
    m1L3Content: "You have the power to choose your beliefs. Every belief is a choice, and every choice shapes your reality. Choose beliefs that empower you, that fill you with energy and possibility.",
    m1L3Exercise: "Write 5 new beliefs you choose for yourself. Start each with 'I am...' or 'I choose to believe...' Read them aloud with conviction.",
    m1L4Title: "Set Your Standards",
    m1L4Content: "Your standards define the minimum you accept for your life. When you raise your standards, you raise your energy. What you tolerate is what you get. What you demand is what you attract.",
    m1L4Exercise: "Define your standards in 3 areas: How you treat yourself, how you allow others to treat you, and what you commit to daily.",
    m1L5Title: "Act On Them",
    m1L5Content: "Identity without action is just a dream. Your new identity needs expression through daily choices, habits, and courage. Every small action aligned with your true self builds momentum.",
    m1L5Exercise: "Choose ONE action today that aligns with your new identity. Do it. Tomorrow, choose another. Build the chain.",

    // Module 2
    m2Title: "Rules",
    m2Subtitle: "Learn the Rules of One Hand",
    m2Description: "Understand the laws. The rules. The Rules of One Hand. Simple principles held in the palm of your hand that govern energy and life.",
    m2L1Title: "The Universal Laws",
    m2L1Content: "Life operates on simple, universal laws — like gravity for the soul. When you understand them, you stop fighting life and start flowing with it. Energy follows attention. Like attracts like. What you give, returns.",
    m2L1Exercise: "Observe today: Where does your attention go? What are you attracting? What patterns do you notice?",
    m2L2Title: "Interactive Hand - Five Rules",
    m2L2Content: "Five fingers, five fundamental rules — always with you, always available. Click on each finger to discover its wisdom. Your hand becomes your guide, your reminder, your compass for navigating life.",
    m2L2Exercise: "Study each finger's rule. Choose one rule to practice today. Touch that finger throughout the day and recall its wisdom.",
    fingerThumb: "Thumb - Everything is Good",
    fingerThumbRule: "Every challenge is an opportunity. A lesson. Life is a school of the spirit. Of spiritual growth.",
    fingerIndex: "Index - You Are the Author",
    fingerIndexRule: "You are responsible for everything that happens in your life. For your health, work, thoughts, emotions, energy, for your inner child and its joy, for what you bring into relationships - whether authenticity, appreciation, attention, interest, support or criticism, indifference, contempt. For your successes and failures at work. And for your personal development.",
    fingerMiddle: "Middle - You Have a Mission",
    fingerMiddleRule: "You have a spark. Something with which you came to enrich the world. To benefit the universal organism. You have your unique function here. Talent and gift.",
    fingerRing: "Ring - Love Yourself, Love Others",
    fingerRingRule: "The quality of your life corresponds to the quality of your relationships. Improve your communication and compassion skills and you will improve your life.",
    fingerPinky: "Pinky - Here and Now",
    fingerPinkyRule: "Joy and gratitude from little things. Rejoice in every HERE AND NOW. Be grateful. Focus your attention on what is good. Sow good deeds and thoughts and good will return to you.",
    
    // Hand exercise
    handTitle: "Rules of One Hand",
    handIntro: "Don't want to crash in life? Learn the rules. Heart on your palm.",
    handDescription: "The rules of one hand will help you navigate life with wisdom and love. Each finger represents a key principle for a fulfilled life.",
    
    // Thumb
    thumbTitle: "Everything is Good",
    thumbPrinciple: "Nothing happens by chance. Every situation has its meaning. I can resist, or accept and understand.",
    thumbQuestions: "Reflective questions:",
    thumbQ1: "What is happening in my life right now?",
    thumbQ2: "Where am I resisting reality?",
    thumbQ3: "What would change if I accepted the situation?",
    thumbExercise: "Write one current situation that is hard for you to accept:",
    thumbButton: "I choose to see it differently",
    thumbAffirmation: "Maybe it's not against me. Maybe it's for me.",
    
    // Index
    indexTitle: "Responsibility",
    indexPrinciple: "I always point only at myself. I accept my share of responsibility for everything that happens in my life.",
    indexQuestions: "Questions:",
    indexQ1: "How did I get into this situation?",
    indexQ2: "What am I supposed to learn?",
    indexQ3: "What can I change?",
    indexExercise: "Write one sentence starting with: 'I accept responsibility for...'",
    indexAffirmation: "By this, I take power back into my own hands.",
    
    // Middle
    middleTitle: "Mission",
    middlePrinciple: "I was born with talent. I have my place and function in the world.",
    middleQuestions: "Questions:",
    middleQ1: "What comes naturally to me?",
    middleQ2: "What fills me with joy?",
    middleQ3: "Where do I feel I contribute to the world?",
    middleExercise: "Write 3 of your talents:",
    middleTalent1: "Talent 1",
    middleTalent2: "Talent 2",
    middleTalent3: "Talent 3",
    middleAffirmation: "When I develop my talents, the world is richer. I feel the meaningfulness of my life.",
    
    // Ring
    ringTitle: "Relationships",
    ringPrinciple: "The quality of my relationships determines the quality of my life. Who I spend time with, I become.",
    ringQuestions: "Questions:",
    ringQ1: "What relationship do I have with myself?",
    ringQ2: "What relationship do I have with life?",
    ringQ3: "Who have I been spending time with lately?",
    ringQ4: "Who inspires me?",
    ringQ5: "Where do I need more kindness?",
    ringQ6: "What can I do for myself today?",
    ringQ7: "What can I do for one of my relationships?",
    ringExercise: "Choose one action:",
    ringOption1: "I will call someone",
    ringOption2: "I will apologize",
    ringOption3: "I will express gratitude",
    ringOption4: "I will take care of my needs",
    ringAffirmation: "Love begins with me.",
    
    // Pinky
    pinkyTitle: "Here and Now",
    pinkyPrinciple: "The most important moment is this one.",
    pinkyQuestions: "Questions:",
    pinkyQ1: "Am I present right now?",
    pinkyQ2: "What am I feeling right now?",
    pinkyQ3: "What do I hear around me?",
    pinkyExercise: "Short mindfulness exercise:",
    pinkyStep1: "1. Inhale",
    pinkyStep2: "2. Exhale",
    pinkyStep3: "3. Notice one detail around you",
    pinkyAffirmation: "This moment is a gift. I appreciate it.",
    
    // Heart
    heartTitle: "AUTHENTICITY",
    heartIntro: "Remember who you truly are. Forget who you think you should be. And who you learned to be to survive in the world.",
    heartQuote: "I have my heart on my palm. I live truthfully. My thoughts, words and actions are in harmony.",
    heartText: "Decide what you want to believe. Be authentic. Authentikos - true, real, genuine. You learned that you must and cannot. It's time to return to I don't have to and I can.",
    heartQuestions: "Reflection:",
    heartQ1: "Where am I not authentic?",
    heartQ2: "Where am I playing a role?",
    heartQ3: "Where do I say yes when I want to say no?",
    heartQ4: "Where am I afraid to stand up for myself to avoid an unpleasant tone, word, or look?",
    heartQ5: "What would I say if I weren't afraid?",
    heartQ6: "What would I do if it didn't feel awkward?",
    heartExercise: "Write one truthful sentence about yourself that you don't usually say:",
    heartAffirmation: "Authenticity is the courage to be real.",
    
    // Common
    saveAnswer: "Save",
    answerSaved: "Answer saved",
    clickFingers: "Click on each finger to discover its wisdom",
    principle: "Principle:",
    exercise: "Exercise:",
    complete: "Complete",
    m2L3Title: "Law of Vibration",
    m2L3Content: "Everything vibrates. Your thoughts, your words, your emotions — all carry a frequency. High vibration attracts high experiences. Low vibration attracts low experiences. You are always broadcasting your frequency to the universe.",
    m2L3Exercise: "Rate your vibration right now (1-10). What would raise it by 1 point? Do that thing now.",
    m2L4Title: "Law of Cause & Effect",
    m2L4Content: "Every action has a consequence. Every thought plants a seed. You are both the gardener and the garden. What you plant today, you harvest tomorrow. Choose your seeds wisely.",
    m2L4Exercise: "Identify 3 'seeds' you've been planting (habits, thoughts, actions). Are they flowers or weeds? Replace one weed with a flower today.",
    m2L5Title: "Law of Energy Conservation",
    m2L5Content: "Energy cannot be created or destroyed — only transformed. Your anger can become passion. Your fear can become courage. Your pain can become wisdom. Learn to transform, not suppress.",
    m2L5Exercise: "Take one negative emotion you feel today. Ask: 'What is the positive transformation of this energy?' Channel it there.",

    // Thumb Exercise
    m2L6Title: "Thumb: Everything is Good - Exercise",
    m2L6Content: "Every challenge is an opportunity. Every lesson is a gift. Life is a school of the spirit. This principle means accepting that life is not random. Every situation, pleasant or challenging, comes with a reason - to teach you, strengthen you, guide you to growth.",
    m2L6Exercise: "Remember a difficult situation from the past. Write: 1) The situation 2) What it taught you 3) How it strengthened you. Affirmation: 'Everything that comes into my life is an opportunity for growth.'",

    // Index Exercise
    m2L7Title: "Index: You Are Responsible - Exercise",
    m2L7Content: "You are responsible for everything that happens in your life. Your health. Your work. Your thoughts. Your emotions. This doesn't mean you're guilty. It means you have the power to change it.",
    m2L7Exercise: "Self-assessment: Rate your responsibility on a scale of 1-10 in areas: Health, Work, Relationships, Finances, Emotions, Inner child, Self-development. Choose the area with the lowest score and write 3 concrete steps for improvement.",

    // Middle Exercise
    m2L8Title: "Middle: You Have a Mission - Exercise",
    m2L8Content: "A spark. Something with which you came to enrich the world. You are here for a reason. You have a unique function in this universal organism. Your talent, your gift awaits to be discovered and used.",
    m2L8Exercise: "Answer: 1) What fills you with joy? 2) What are you naturally good at? 3) What would the world lose if you weren't here? 4) What problem do you want to help solve? Write: 'I am here to...'",

    // Ring Exercise
    m2L9Title: "Ring: Relationships - Exercise",
    m2L9Content: "Quality of relationships = quality of life. Improve your communication and compassion skills and you will improve your life. Your relationships are a mirror of your inner self.",
    m2L9Exercise: "Relationship inventory: List 5 most important relationships. Rate quality 1-10. For each write: 'What can I improve?' (Not what they should improve). Choose one difficult relationship and try to empathize with the other person.",

    // Pinky Exercise
    m2L10Title: "Pinky: Here and Now - Exercise",
    m2L10Content: "Joy and gratitude from little things. Happiness is not in the future. It is right now. In a cup of coffee. In a stranger's smile. In a ray of sunshine.",
    m2L10Exercise: "Gratitude practice: Each day write down 3 little things you're grateful for. Mindfulness exercise: Once a day for 2 minutes stop everything. Close your eyes. Notice: your breath, sounds around, feeling of feet on the ground.",

    // Final Commitment
    m2L11Title: "Module Conclusion: Your Commitment",
    m2L11Content: "Identity is not what others say about you. Identity is not what you thought about yourself. Identity is a choice. Now that you know the rules of one hand, it's time to decide. What will you believe about yourself? What will you believe about the world? What will you believe about life?",
    m2L11Exercise: "Write your personal manifest - your new beliefs. Then write your commitment: 'I, [your name], choose to live according to the rules of one hand. I accept responsibility for my life. I seek my mission. I care for relationships. And I find joy in the present moment.' Sign and date.",

    // Module 3
    m3Title: "Navigation",
    m3Subtitle: "Power of Focus & Language",
    m3Description: "What you say is what you live. What you frequently think about is what you live. Choose your thoughts wisely. Don't let the weed grow in your mind.",
    m3L1Title: "Power of Focus",
    m3L1Content: "Where focus goes, energy flows. Your attention is the most valuable resource you have. What you focus on expands. Focus on problems, you get more problems. Focus on solutions, you get more solutions.",
    m3L1Exercise: "Set 3 positive focus points for today. Every time your mind wanders to negativity, gently redirect to one of these points.",
    m3L2Title: "Power of Language",
    m3L2Content: "Words are spells — that's why it's called spelling. Every word you speak programs your subconscious mind and shapes your reality. 'I can't' vs. 'I'm learning.' 'I have to' vs. 'I choose to.'",
    m3L2Exercise: "For 24 hours, notice every negative phrase you say. Replace each one: 'I can't' → 'I'm learning to', 'I have to' → 'I get to', 'It's impossible' → 'I haven't found the way yet'.",
    m3L3Title: "Keep Your Mental Fireplace Clean",
    m3L3Content: "Keep the fireplace of your thoughts clean — you will build peace and be happy. Your mind is like a fireplace: feed it quality fuel and it warms your whole life. Feed it garbage and it fills your house with smoke.",
    m3L3Exercise: "Identify your top 3 'mental pollutants' (negative news, toxic conversations, worry loops). Create a plan to reduce each by 50% this week.",
    m3L4Title: "RICH Mindset vs. POOR Mindset",
    m3L4Content: "POOR mindset leads to poor energy, poor relationships, poor communication, poor habits, poor financial situation. RICH mindset: R — Real, Respect, Relax, Read. I — Intuition, Invention, Investing in yourself. CH — Copy Happy Habits, Create Happy Habits.",
    m3L4Exercise: "Score yourself on each RICH letter (1-10). R: How real, respectful, relaxed are you? Do you read? I: Do you follow intuition? Invent solutions? Invest in growth? CH: What happy habits do you copy/create?",
    m3L5Title: "Set Your Navigation",
    m3L5Content: "A ship without a destination drifts. Set your internal GPS. Your vision, your values, your daily intentions — these are your coordinates. Review them daily. Adjust course as needed. But always know where you're heading.",
    m3L5Exercise: "Write your life navigation statement: 'I am heading toward... guided by... My daily compass points are...' Read it every morning this week.",

    // Module 4
    m4Title: "Energy",
    m4Subtitle: "Maintain Balance",
    m4Description: "All aspects need fueling. Fuel frequently so that your energy is high and you can pour it into your relationships, projects, and hobbies.",
    m4L1Title: "The Three Pillars",
    m4L1Content: "You are a being of three dimensions: body, mind, and soul. Like a three-legged stool, if one leg is weak, everything wobbles. True balance means nourishing all three — daily, intentionally, joyfully.",
    m4L1Exercise: "Rate each pillar today (1-10): Body — how do you feel physically? Mind — how clear and positive is your thinking? Soul — how connected do you feel to your purpose and joy?",
    m4L2Title: "Fuel Your Body",
    m4L2Content: "Your body is your vehicle for this journey. Treat it like the most precious machine on Earth. Movement, nutrition, rest, and breath — these are your four fuel types. Neglect none.",
    m4L2Exercise: "Choose one body upgrade for this week: 10 minutes of movement daily, one more glass of water, 30 minutes earlier to bed, or 5 minutes of deep breathing.",
    m4L3Title: "Fuel Your Mind",
    m4L3Content: "Your mind needs quality input to produce quality output. Feed it wisdom, inspiration, and new perspectives. Protect it from noise, negativity, and mindless consumption. A well-fed mind is your greatest asset.",
    m4L3Exercise: "Start a 'mind diet': Replace 30 minutes of screen scrolling with reading, learning, or creative thinking. Track it for 7 days.",
    m4L4Title: "Fuel Your Soul",
    m4L4Content: "Your soul craves meaning, connection, beauty, and stillness. It speaks in whispers — through intuition, goosebumps, tears of joy, and moments of awe. Create space to hear it.",
    m4L4Exercise: "Give your soul 15 minutes today: meditation, nature walk, journaling, music, art, or simply sitting in silence. Notice what arises.",
    m4L5Title: "Living with Elevated Energy",
    m4L5Content: "When body, mind, and soul are aligned and fueled, you enter a state of elevated energy — high vibration of love, unity, wisdom, and joy. From this state, everything flows. You give more, receive more, and live more.",
    m4L5Exercise: "Design your 'Elevated Energy Morning Routine' — include one practice for body, one for mind, one for soul. Commit to it for 7 days.",

    // Module 5
    m5Title: "Relationships",

    // Module 6 - Final Integration
    m6Title: "INTEGRATION",
    m6Subtitle: "Your Driver's License for Life",
    m6Description: "Summary and integration of your entire journey. Receive your symbolic Driver's License for Life.",
    m5Subtitle: "Go, Laugh, Share",
    m5Description: "Go, smile, and share your gifts with the world. Give and accept what the world and others offer you. Life is meaningful only when we give and receive.",
    m5L1Title: "Your Unique Gifts",
    m5L1Content: "You came into this world with gifts that no one else has in exactly the same way. Your combination of talents, experiences, perspective, and energy is unique. The world needs what only you can give.",
    m5L1Exercise: "Ask 3 people close to you: 'What do you think is my greatest gift to others?' Write down their answers. Look for the pattern.",
    m5L2Title: "The Joy of Giving",
    m5L2Content: "Giving raises your vibration instantly. Not giving from emptiness or obligation, but from overflow. When you give from a full cup, both the giver and receiver are elevated. This is the secret to lasting happiness.",
    m5L2Exercise: "Perform 3 acts of genuine giving today: a compliment, help, your time, a smile, encouragement. Notice how YOUR energy changes with each act.",
    m5L3Title: "The Art of Receiving",
    m5L3Content: "Many people can give but cannot receive. Receiving is also a gift — to the giver. When you gracefully accept help, love, compliments, or abundance, you complete the circle of energy flow.",
    m5L3Exercise: "Today, practice receiving fully. When someone compliments you, say 'Thank you' without deflecting. When offered help, accept it. Notice your resistance and let it soften.",
    m5L4Title: "Building Meaningful Connections",
    m5L4Content: "We are not meant to walk alone. Quality connections amplify your energy exponentially. Surround yourself with people who see your light and encourage your growth. Be that person for others.",
    m5L4Exercise: "Reach out to someone you haven't connected with in a while. Share something genuine. Ask how they truly are. Listen deeply.",
    m5L5Title: "Share Your Light",
    m5L5Content: "You have completed the five powers. You understand your identity, the laws, your navigation, your balance, and the power of connection. Now go — smile, shine, and share your light. The world is waiting for you.",
    m5L5Exercise: "Write a letter to yourself from your future self — the version of you who lives with high energy every day. What does that person want you to know? Carry this letter with you.",

    // Common
    reflection: "Your Reflection",
    reflectionPlaceholder: "Write your thoughts, insights, and discoveries...",
    exercise: "Practice Exercise",
    save: "Save",
    saved: "Saved!",
    next: "Next",
    previous: "Previous",
    complete: "Mark Complete",
    
    // Progress
    overallProgress: "Overall Progress",
    modulesCompleted: "Modules Completed",
    lessonsCompleted: "Lessons Completed",
    currentStreak: "Current Streak",
    days: "days",
    energyTrend: "Energy Trend",
    yourJourney: "Your Transformation Journey",
    
    // Language
    language: "Language",
    switchLang: "Čeština",

    // Final Module
    fm_step1_title: "You're not collecting information anymore.",
    fm_step1_subtitle: "You're integrating your life.",
    fm_step1_button: "Enter the path",
    fm_step2_title: "Looking Back",
    fm_step2_subtitle: "What am I taking from each module?",
    fm_step2_takeaway: "What I'm taking",
    fm_step2_practice: "What I live in practice",
    fm_step3_title: "Your life as a car",
    fm_step3_subtitle: "All parts must work harmoniously",
    fm_step3_driver: "Driver",
    fm_step3_gps: "GPS",
    fm_step3_fuel: "Fuel",
    fm_step3_passengers: "Passengers",
    fm_step3_q_driver: "Who am I really?",
    fm_step3_q_gps: "Where am I heading in life?",
    fm_step3_q_fuel: "What fills me with energy?",
    fm_step3_q_passengers: "Who do I want to travel through life with?",
    fm_step4_title: "Your action plan",
    fm_step4_subtitle: "Gradual steps to your new life",
    fm_step4_30days: "30 days",
    fm_step4_90days: "90 days",
    fm_step4_1year: "1 year",
    fm_step5_title: "Your inner compass",
    fm_step5_subtitle: "Choose your TOP 5 values",
    fm_step5_family: "Family",
    fm_step5_health: "Health",
    fm_step5_career: "Career",
    fm_step5_friendship: "Friendship",
    fm_step5_growth: "Spiritual growth",
    fm_step5_creativity: "Creativity",
    fm_step5_freedom: "Freedom",
    fm_step5_security: "Security",
    fm_step5_service: "Service to others",
    fm_step5_joy: "Fun/joy",
    fm_step6_title: "Your vision",
    fm_step6_subtitle: "Imagine your life",
    fm_step6_1year: "In 1 year",
    fm_step6_5years: "In 5 years",
    fm_step6_legacy: "My legacy",
    fm_step7_title: "Daily rituals",
    fm_step7_subtitle: "Anchoring in everyday life",
    fm_step7_morning: "Morning ritual",
    fm_step7_evening: "Evening ritual",
    fm_step7_weekly: "Weekly ritual",
    fm_step8_title: "Your life manifest",
    fm_step8_subtitle: "Your new conviction",
    fm_step9_title: "Where are you now?",
    fm_step9_subtitle: "Reflection of your progress",
    fm_step9_identity: "I live according to my true identity",
    fm_step9_mindset: "I have a RICH mindset",
    fm_step9_energy: "I take care of my energy",
    fm_step9_relationships: "I have harmonious relationships",
    fm_step9_fulfillment: "I feel fulfilled",
    fm_step10_title: "Obstacles",
    fm_step10_subtitle: "What can stop you - and how to overcome it",
    fm_step10_time: "I don't have time",
    fm_step10_hard: "It's too hard",
    fm_step10_failed: "I failed again",
    fm_step10_support: "People around me don't support me",
    fm_step10_doubt: "I don't know if it makes sense",
    fm_step11_title: "Initiatory ritual",
    fm_step11_subtitle: "Your commitment to a new life",
    fm_step11_name: "Your name",
    fm_step11_date: "Today's date",
    fm_step11_signature: "Signature",
    fm_issued: "DRIVING LICENCE FOR LIFE",
    fm_issued_subtitle: "ISSUED",
    fm_final_message: "Now just drive. The world needs your light.",
    fm_continue: "Continue",
    fm_back: "Back",
    fm_saving: "Saving...",
    },
  cs: {
    // Navigation
    home: "Domů",
    modules: "Moduly",
    progress: "Moje cesta",
    dailyCheckIn: "Denní check-in",
    
    // Home
    welcomeTitle: "Řidičák na život",
    welcomeSubtitle: "Pro váš spokojený život",
    welcomeSubtitle2: "Bez kompromisů",
    welcomeDescription: "Objevte pět klíčových modulů, které vás provedou cestou k autentickému, naplněnému a šťastnému životu. Vzpomeňte si, kdo opravdu jste.",
    startJourney: "Začít cestu",
    exploreModules: "Prozkoumat moduly",
    continueJourney: "Pokračuj v cestě",
    todayEnergy: "Dnešní energie",
    statsModules: "Modulů",
    statsExercises: "Cvičení",
    courseDescription: "5 transformačních modulů",
    courseSubDescription: "Tvá cesta k spokojenému životu",
    courseDetailText: "Každý modul tě provede klíčovými oblastmi osobního růstu. Postupuj vlastním tempem a objevuj svůj potenciál.",
    
    // Energy Check-in
    howAreYou: "Jaká je dnes tvoje energie?",
    energyLevel: "Úroveň energie",
    yourMood: "Tvoje nálada",
    radiant: "Zářivá",
    positive: "Pozitivní",
    neutral: "Neutrální",
    low: "Nízká",
    struggling: "Těžká",
    addNote: "Přidej reflexi...",
    saveCheckIn: "Uložit check-in",
    checkInSaved: "Check-in uložen!",
    
    // Modules
    module: "Modul",
    modulesTitle: "5 transformačních modulů",
    moduleSubtitle: "Tvá cesta k spokojenému životu. Každý modul tě provede klíčovými oblastmi osobního růstu.",
    locked: "Nejprve dokonči předchozí modul",
    lessons: "Lekce",
    completed: "Dokončeno",
    startModule: "Začít modul",
    continueModule: "Pokračovat",
    
    // Module 1
    m1Title: "Identita",
    m1Subtitle: "Vzpomeň si, kdo opravdu jsi",
    m1Description: "Zapomeň, co ses naučil. Vzpomeň si, kdo doopravdy jsi. Rozhodni se, čemu chceš věřit. Nastav si vlastní standardy. A jednej podle nich.",
    m1L1Title: "Zapomeň, co ses naučil",
    m1L1Content: "Většina toho, čemu o sobě věříme, nám byla dána ostatními — rodiči, učiteli, společností. Tyto přesvědčení nás formovala, ale nejsou to my. Dnes začínáme tím, že pustíme půjčené identity.",
    m1L1Exercise: "Napiš 3 přesvědčení o sobě, která jsi přijal od druhých. U každého se zeptej: 'Je tohle opravdu moje? Slouží to mému nejvyššímu já?'",
    m1L2Title: "Vzpomeň si, kdo doopravdy jsi",
    m1L2Content: "TVÉ POJETÍ SEBE SAMA — kdo si myslíš, že jsi — určuje, jak se každý den chováš, myslíš, jak se oblékáš, jak o sebe pečuješ, jak mluvíš, jak chodíš, s kým se stýkáš. A určuje také, jak se k tobě chovají a jak Tě vidí druzí. Kdo jsi? Jsi žebrák, chudák, holčička, chlapeček — nebo královna, král? Pod všemi vrstvami podmíněnosti leží tvá pravá podstata — čistá energie, čistý potenciál, čistá láska. Nejsi svá práce, minulost ani chyby. Jsi vědomí prožívající život.",
    m1L2Exercise: "Zavři oči na 5 minut. Dýchej zhluboka. Zeptej se sám sebe: 'Kdo jsem bez svého příběhu?' Zapiš, co ti přijde.",
    m1L3Title: "Rozhodni se, čemu věřit",
    m1L3Content: "Máš moc si vybrat svá přesvědčení. Každé přesvědčení je volba a každá volba formuje tvou realitu. Vyber si přesvědčení, která tě posilují, naplňují energií a možnostmi.",
    m1L3Exercise: "Napiš 5 nových přesvědčení, která si volíš. Začni každé 'Já jsem...' nebo 'Věřím, že...' Přečti je nahlas s přesvědčením.",
    m1L4Title: "Nastav si standardy",
    m1L4Content: "Tvé standardy definují minimum, které přijímáš pro svůj život. Když zvýšíš standardy, zvýšíš energii. Co toleruješ, to dostáváš. Co vyžaduješ, to přitahuješ.",
    m1L4Exercise: "Definuj své standardy ve 3 oblastech: Jak se chováš k sobě, jak dovolíš druhým, aby se k tobě chovali, a co děláš každý den.",
    m1L5Title: "Jednej podle nich",
    m1L5Content: "Identita bez akce je jen sen. Tvá nová identita potřebuje vyjádření skrze denní volby, návyky a odvahu. Každá malá akce v souladu s tvým pravým já buduje momentum.",
    m1L5Exercise: "Vyber si JEDNU akci dnes, která je v souladu s tvou novou identitou. Udělej ji. Zítra vyber další. Buduj řetězec.",

    // Module 2
    m2Title: "Pravidla",
    m2Subtitle: "Nauč se pravidla jedné ruky",
    m2Description: "Pochop zákony. Pravidla. Pravidla jedné ruky. Jednoduché principy v dlani tvé ruky, které řídí energii a život.",
    m2L1Title: "Univerzální zákony",
    m2L1Content: "Život funguje na jednoduchých, univerzálních zákonech — jako gravitace pro duši. Když je pochopíš, přestaneš bojovat se životem a začneš s ním plynout. Energie následuje pozornost. Stejné přitahuje stejné.",
    m2L1Exercise: "Pozoruj dnes: Kam jde tvá pozornost? Co přitahuješ? Jaké vzorce si všímáš?",
    m2L2Title: "Interaktivní ruka - Pět pravidel",
    m2L2Content: "Pět prstů, pět základních pravidel — vždy s tebou, vždy dostupných. Klikni na každý prst a objevíš jeho moudrost. Tvá ruka se stane tvým průvodcem, připomínkou, kompasem pro navigaci životem.",
    m2L2Exercise: "Prostuduj pravidlo každého prstu. Vyber si jedno pravidlo, které dnes budeš praktikovat. Během dne se dotkni toho prstu a vzpomeň si na jeho moudrost.",
    fingerThumb: "Palec - Vše je dobré",
    fingerThumbRule: "Každá výzva je příležitost. Lekce. Život je škola ducha. Duchovního růstu.",
    fingerIndex: "Ukazováček - Ty jsi autor",
    fingerIndexRule: "Ty jsi zodpovědný za vše, co se ve tvém životě děje. Za své zdraví, práci, myšlenky, emoce, energii, za své vnitřní dítě a jeho radost, za to co přinášíš do vztahů - zda autenticitu, ocenění, pozornost, zájem, podporu nebo kritiku, nezájem, opovržení. Za své úspěchy i neúspěchy v práci. A za svůj osobní rozvoj.",
    fingerMiddle: "Prostředník - Máš poslání",
    fingerMiddleRule: "Máš jiskru. Něco, čím jsi přišel obohatit svět. Prospět vesmírnému organismu. Máš zde svou jedinečnou funkci. Talent a dar.",
    fingerRing: "Prsteník - Miluj SEBE, miluj druhé",
    fingerRingRule: "Kvalita tvého života odpovídá kvalitě tvých vztahů. Zlepši dovednost komunikace a soucitu a zlepšíš svůj život.",
    fingerPinky: "Malíček - Tady a teď",
    fingerPinkyRule: "Radost a vděčnost z maličkostí. Raduj se v každém TADY A TEĎ. Buď vděčný. Zaměřuj pozornost na to, co je dobré. Raduj se člověče z dobré úrody. Sej dobré činy a myšlenky a dobro se Ti vrátí.",
    
    // Hand exercise
    handTitle: "Pravidla jedné ruky",
    handIntro: "Nechceš v životě bourat? Nauč se pravidla. Srdce na dlani.",
    handDescription: "Pravidla jedné ruky ti pomohou navigovat životem s moudrostí a láskou. Každý prst představuje klíčový princip pro spokojený život.",
    
    // Thumb
    thumbTitle: "Vše je dobré",
    thumbPrinciple: "Nic se neděje náhodou. Každá situace má svůj význam. Mohu odporovat, nebo přijmout a porozumět.",
    thumbQuestions: "Reflexivní otázky:",
    thumbQ1: "Co se mi teď v životě děje?",
    thumbQ2: "Kde odporuji realitě?",
    thumbQ3: "Co by se změnilo, kdybych situaci přijal/a?",
    thumbExercise: "Napiš jednu aktuální situaci, kterou je pro tebe těžké přijmout:",
    thumbButton: "Rozhoduji se to vidět jinak",
    thumbAffirmation: "Možná to není proti mně. Možná je to pro mě.",
    
    // Index
    indexTitle: "Zodpovědnost",
    indexPrinciple: "Ukazuji vždy jen na sebe. Přijímám svůj díl odpovědnosti za vše, co se v mém životě děje.",
    indexQuestions: "Otázky:",
    indexQ1: "Jak jsem se do této situace dostal/a?",
    indexQ2: "Co se mám naučit?",
    indexQ3: "Co mohu změnit já?",
    indexExercise: "Napiš jednu větu začínající: 'Přijímám odpovědnost za...'",
    indexAffirmation: "Tímto přebírám sílu zpět do svých rukou.",
    
    // Middle
    middleTitle: "Poslání",
    middlePrinciple: "Narodil/a jsem se s talentem. Mám na světě své místo a svou funkci.",
    middleQuestions: "Otázky:",
    middleQ1: "Co mi jde přirozeně?",
    middleQ2: "Co mě naplňuje radostí?",
    middleQ3: "Kde cítím, že přispívám světu?",
    middleExercise: "Napiš 3 své talenty:",
    middleTalent1: "Talent 1",
    middleTalent2: "Talent 2",
    middleTalent3: "Talent 3",
    middleAffirmation: "Když rozvíjím své talenty, svět je bohatší. Vnímám smysluplnost svého života.",
    
    // Ring
    ringTitle: "Vztahy",
    ringPrinciple: "Kvalita mých vztahů určuje kvalitu mého života. S kým se stýkám, tím se stávám.",
    ringQuestions: "Otázky:",
    ringQ1: "Jaký vztah mám sama k sobě?",
    ringQ2: "Jaký vztah mám k životu?",
    ringQ3: "S kým se poslední dobou nejvíce stýkám?",
    ringQ4: "Kdo mě inspiruje?",
    ringQ5: "Kde potřebuji více laskavosti?",
    ringQ6: "Co mohu dnes udělat sama pro sebe?",
    ringQ7: "Co mohu udělat pro nějaký svůj vztah?",
    ringExercise: "Vyber si jednu akci:",
    ringOption1: "Zavolám někomu",
    ringOption2: "Omluvím se",
    ringOption3: "Vyjádřím vděčnost",
    ringOption4: "Postarám se o své potřeby",
    ringAffirmation: "Láska začíná u mě.",
    
    // Pinky
    pinkyTitle: "Tady a teď",
    pinkyPrinciple: "Nejdůležitější okamžik je tento.",
    pinkyQuestions: "Otázky:",
    pinkyQ1: "Jsem právě teď přítomen/přítomná?",
    pinkyQ2: "Co právě cítím?",
    pinkyQ3: "Co slyším kolem sebe?",
    pinkyExercise: "Krátké mindfulness cvičení:",
    pinkyStep1: "1. Nádech",
    pinkyStep2: "2. Výdech",
    pinkyStep3: "3. Všimni si jednoho detailu kolem sebe",
    pinkyAffirmation: "Tento okamžik je dar. Oceňuji ho.",
    
    // Heart
    heartTitle: "AUTENTICITA",
    heartIntro: "Vzpomeň si, kdo opravdy jsi. Zapomeň, kdo si myslíš, že máš být. A kdo ses naučil být, abys ve světě obstál.",
    heartQuote: "Mám srdce na dlani. Žiju pravdivě. Mé myšlenky, slova a činy jsou v souladu.",
    heartText: "Rozhodni se, čemu chceš věřit. Buď autentický. Authentikos - pravý, opravdový, nefalšovaný. Naučil ses, že musíš a nemůžeš. Je čas vrátit se k nemusím a mohu.",
    heartQuestions: "Reflexe:",
    heartQ1: "Kde nejsem autentický/autentická?",
    heartQ2: "Kde hraji roli?",
    heartQ3: "Kde říkám ano, když chci říct ne?",
    heartQ4: "Kde se bojím stát sám za sebou, abych se vyhnul nepříjemnému tónu, slovu, pohledu?",
    heartQ5: "Co bych řekl/a, kdybych se nebál/a?",
    heartQ6: "Co bych udělal/a, kdyby mi to nebylo blbý?",
    heartExercise: "Napiš jednu pravdivou větu o sobě, kterou běžně neříkáš:",
    heartAffirmation: "Autenticita je odvaha být skutečný/á.",
    
    // Common
    saveAnswer: "Uložit",
    answerSaved: "Odpověď uložena",
    clickFingers: "Klikni na každý prst a objevíš jeho moudrost",
    principle: "Princip:",
    exercise: "Cvičení:",
    complete: "Dokončit",
    m2L3Title: "Zákon vibrace",
    m2L3Content: "Vše vibruje. Tvé myšlenky, slova, emoce — vše nese frekvenci. Vysoká vibrace přitahuje vysoké zážitky. Nízká vibrace přitahuje nízké zážitky. Vždy vysíláš svou frekvenci do vesmíru.",
    m2L3Exercise: "Ohodnoť svou vibraci právě teď (1-10). Co by ji zvýšilo o 1 bod? Udělej tu věc hned.",
    m2L4Title: "Zákon příčiny a následku",
    m2L4Content: "Každá akce má důsledek. Každá myšlenka zasadí semínko. Jsi zahradníkem i zahradou zároveň. Co zasadíš dnes, sklidíš zítra. Vyber svá semínka moudře.",
    m2L4Exercise: "Identifikuj 3 'semínka', která jsi sázel (návyky, myšlenky, činy). Jsou to květiny nebo plevel? Nahraď dnes jeden plevel květinou.",
    m2L5Title: "Zákon zachování energie",
    m2L5Content: "Energie nemůže být vytvořena ani zničena — pouze transformována. Tvůj hněv se může stát vášní. Tvůj strach odvahou. Tvá bolest moudrostí. Nauč se transformovat, ne potlačovat.",
    m2L5Exercise: "Vezmi jednu negativní emoci, kterou dnes cítíš. Zeptej se: 'Jaká je pozitivní transformace této energie?' Nasměruj ji tam.",

    // Thumb Exercise
    m2L6Title: "Palec: Vše je dobré - Cvičení",
    m2L6Content: "Každá výzva je příležitost. Každá lekce je dar. Život je škola ducha. Tento princip znamená přijmout, že život není náhoda. Každá situace, ať už příjemná nebo náročná, přichází s důvodem - učit tě, posilovat, vést k růstu.",
    m2L6Exercise: "Vzpomeň si na obtížnou situaci z minulosti. Napiš: 1) Situaci 2) Co tě naučila 3) Jak tě to posílilo. Afirmace: 'Vše, co přichází do mého života, je příležitost k růstu.'",

    // Index Exercise
    m2L7Title: "Ukazováček: Zodpovědnost - Cvičení",
    m2L7Content: "Za vše, co se ve tvém životě děje, jsi zodpovědný/á ty. Tvé zdraví. Tvá práce. Tvé myšlenky. Tvé emoce. To neznamená, že jsi vinna/vinen. Znamená to, že máš moc to změnit.",
    m2L7Exercise: "Sebehodnocení: Ohodnoť na škále 1-10 svou zodpovědnost v oblastech: Zdraví, Práce, Vztahy, Finance, Emoce, Vnitřní dítě, Seberozvoj. Vyber oblast s nejnižším skóre a napiš 3 konkrétní kroky ke zlepšení.",

    // Middle Exercise
    m2L8Title: "Prostředníček: Poslání - Cvičení",
    m2L8Content: "Jiskru. Něco, čím jsi přišel/přišla obohatit svět. Jsi tu z nějakého důvodu. Máš jedinečnou funkci v tomto vesmírném organismu. Tvůj talent, tvůj dar čeká, až ho odhalíš a použiješ.",
    m2L8Exercise: "Odpověz: 1) Co tě naplňuje radostí? 2) V čem jsi přirozeně dobrý/á? 3) Co by svět ztratil, kdybys tu nebyl/a? 4) Jaký problém chceš pomoci řešit? Napiš: 'Jsem tu, abych...'",

    // Ring Exercise
    m2L9Title: "Prsteníček: Vztahy - Cvičení",
    m2L9Content: "Kvalita vztahů = kvalita života. Zlepši dovednost komunikace a soucitu a zlepšíš svůj život. Tvé vztahy jsou zrcadlem tvého nitra.",
    m2L9Exercise: "Inventura vztahů: Vypiš 5 nejdůležitějších vztahů. Ohodnoť kvalitu 1-10. U každého napiš: 'Co mohu zlepšit JÁ?' (Ne co by měl zlepšit on/ona). Vyber jeden obtížný vztah a zkus se vcítit do druhého člověka.",

    // Pinky Exercise
    m2L10Title: "Malíček: Tady a teď - Cvičení",
    m2L10Content: "Radost a vděčnost z maličkostí. Štěstí není v budoucnosti. Je právě teď. V šálku kávy. V úsměvu cizího člověka. V paprsku slunce.",
    m2L10Exercise: "Praxe vděčnosti: Každý den si zapiš 3 maličkosti, za které jsi vděčný/á. Mindfulness cvičení: Jednou denně na 2 minuty zastav vše. Zavři oči. Vnímej: svůj dech, zvuky kolem, pocit nohou na zemi.",

    // Final Commitment
    m2L11Title: "Závěr modulu: Tvůj závazek",
    m2L11Content: "Identita není to, co o tobě říkají druzí. Identita není to, co sis o sobě myslel/a. Identita je volba. Teď, když znáš pravidla jedné ruky, je čas rozhodnout se. Čemu budeš věřit o sobě? Čemu budeš věřit o světě? Čemu budeš věřit o životě?",
    m2L11Exercise: "Napiš svůj osobní manifest - tvá nová přesvědčení. Pak napiš svůj závazek: 'Já, [tvé jméno], se rozhoduji žít podle pravidel jedné ruky. Přijímám zodpovědnost za svůj život. Hledám své poslání. Pečuji o vztahy. A nacházím radost v přítomném okamžiku.' Podepis a datuj.",

    // Module 3
    m3Title: "Navigace",
    m3Subtitle: "Síla Zaměření a Jazyka",
    m3Description: "Co říkáš, to žiješ. Na co často myslíš, to žiješ. Vyber si myšlenky moudře. Nenech plevel růst ve své mysli.",
    m3L1Title: "Síla zaměření",
    m3L1Content: "Kam jde pozornost, tam proudí energie. Tvá pozornost je nejcennější zdroj, který máš. Na co se zaměříš, to se rozrůstá. Zaměř se na problémy — dostaneš víc problémů. Na řešení — dostaneš víc řešení.",
    m3L1Exercise: "Nastav si 3 pozitivní body zaměření na dnešek. Pokaždé, když se tvá mysl zatoulá k negativitě, jemně ji přesměruj k jednomu z těchto bodů.",
    m3L2Title: "Síla jazyka",
    m3L2Content: "Slova jsou kouzla. Každé slovo, které vyslovíš, programuje tvé podvědomí a formuje tvou realitu. 'Nemůžu' vs. 'Učím se.' 'Musím' vs. 'Chci.'",
    m3L2Exercise: "Po 24 hodin si všímej každé negativní fráze, kterou řekneš. Nahraď každou: 'Nemůžu' → 'Učím se', 'Musím' → 'Rozhoduji se', 'To nejde' → 'Ještě jsem nenašel cestu'.",
    m3L3Title: "Udržuj krb myšlenek čistý",
    m3L3Content: "Udržuj krb svých myšlenek čistý, založíš tak mír a budeš šťastný. Tvá mysl je jako krb: nakrmíš-li ji kvalitním palivem, zahřeje celý tvůj život. Nakrmíš-li ji odpadky, naplní tvůj dům kouřem.",
    m3L3Exercise: "Identifikuj své 3 hlavní 'mentální znečišťovatele' (negativní zprávy, toxické rozhovory, smyčky starostí). Vytvoř plán, jak každý z nich snížit o 50 % tento týden.",
    m3L4Title: "RICH myšlení vs. POOR myšlení",
    m3L4Content: "POOR myšlení vede k slabé energii, slabým vztahům, slabé komunikaci, špatným návykům, špatné finanční situaci. RICH myšlení: R — Reálný, Respekt, Relaxace, Čtení. I — Intuice, Invence, Investice do sebe. CH — Kopíruj Šťastné Návyky, Vytváře Šťastné Návyky.",
    m3L4Exercise: "Ohodnoť se v každém písmenu RICH (1-10). R: Jak jsi reálný, respektující, relaxovaný? Čteš? I: Následuješ intuici? Vymýšlíš řešení? Investuješ do růstu? CH: Jaké šťastné návyky kopíruješ/vytváříš?",
    m3L5Title: "Nastav svou navigaci",
    m3L5Content: "Loď bez cíle se jen potácí. Nastav svůj vnitřní GPS. Tvá vize, hodnoty, denní záměry — to jsou tvé souřadnice. Kontroluj je denně. Přizpůsobuj kurz. Ale vždy věz, kam míříš.",
    m3L5Exercise: "Napiš svůj navigační výrok: 'Směřuji k... veden/a... Mé denní body kompasu jsou...' Čti ho každé ráno tento týden.",

    // Module 4
    m4Title: "Energie",
    m4Subtitle: "Udržuj rovnováhu",
    m4Description: "Všechny aspekty potřebují palivo. Doplňuj často, aby tvá energie byla vysoká a mohl jsi ji vlévat do vztahů, projektů a koníčků.",
    m4L1Title: "Tři pilíře",
    m4L1Content: "Jsi bytost tří dimenzí: tělo, mysl a duše. Jako trojnožka — je-li jedna noha slabá, vše se kýve. Pravá rovnováha znamená vyživovat všechny tři — denně, záměrně, radostně.",
    m4L1Exercise: "Ohodnoť každý pilíř dnes (1-10): Tělo — jak se cítíš fyzicky? Mysl — jak čisté a pozitivní je tvé myšlení? Duše — jak propojeně se cítíš se svým účelem a radostí?",
    m4L2Title: "Vyživ své tělo",
    m4L2Content: "Tvé tělo je tvůj prostředek pro tuto cestu. Zacházej s ním jako s nejcennějším strojem na Zemi. Pohyb, výživa, odpočinek a dech — to jsou tvé čtyři druhy paliva.",
    m4L2Exercise: "Vyber si jedno vylepšení těla na tento týden: 10 minut pohybu denně, jedna sklenice vody navíc, 30 minut dříve do postele, nebo 5 minut hlubokého dýchání.",
    m4L3Title: "Vyživ svou mysl",
    m4L3Content: "Tvá mysl potřebuje kvalitní vstup, aby produkovala kvalitní výstup. Krmí ji moudrostí, inspirací a novými perspektivami. Chraň ji před hlukem, negativitou a bezmyšlenkovitou konzumací.",
    m4L3Exercise: "Začni 'mentální dietu': Nahraď 30 minut scrollování čtením, učením nebo kreativním myšlením. Sleduj to 7 dní.",
    m4L4Title: "Vyživ svou duši",
    m4L4Content: "Tvá duše touží po smyslu, propojení, kráse a tichu. Mluví šeptem — skrze intuici, husí kůži, slzy radosti a okamžiky úžasu. Vytvoř prostor, abys ji slyšel.",
    m4L4Exercise: "Věnuj své duši 15 minut dnes: meditace, procházka přírodou, deník, hudba, umění, nebo jen tiché sezení. Všimni si, co se vynoří.",
    m4L5Title: "Život s povznesenou energií",
    m4L5Content: "Když jsou tělo, mysl a duše v souladu a vyživeny, vstoupíš do stavu povznesené energie — vysoké vibrace lásky, jednoty, moudrosti a radosti. Z tohoto stavu vše plyne.",
    m4L5Exercise: "Navrhni svou 'Ranní rutinu povznesené energie' — zahrň jednu praktiku pro tělo, jednu pro mysl, jednu pro duši. Zavázej se k ní na 7 dní.",

    // Module 5
    m5Title: "Vztahy",

    // Modul 6 - Finální integrace
    m6Title: "INTEGRACE",
    m6Subtitle: "Tvůj řidičák na život",
    m6Description: "Shrnutí a integrace celé tvé cesty. Získej symbolický Řidičák na život.",
    m5Subtitle: "Jeď, směj se, rozdávej",
    m5Description: "Jdi, usměj se a sdílej své dary se světem. Dávej a přijímej, co svět a ostatní nabízejí. Život má smysl, jen když dáváme a přijímáme.",
    m5L1Title: "Tvé jedinečné dary",
    m5L1Content: "Přišel jsi na tento svět s dary, které nikdo jiný nemá přesně stejné. Tvá kombinace talentů, zkušeností, pohledu a energie je jedinečná. Svět potřebuje to, co můžeš dát jen ty.",
    m5L1Exercise: "Zeptej se 3 blízkých lidí: 'Co je podle tebe můj největší dar ostatním?' Zapiš si odpovědi. Hledej vzorec.",
    m5L2Title: "Radost z dávání",
    m5L2Content: "Dávání okamžitě zvyšuje tvou vibraci. Ne dávání z prázdna nebo povinnosti, ale z přetékání. Když dáváš z plného poháru, oba — dárce i příjemce — jsou povzneseni.",
    m5L2Exercise: "Vykonej dnes 3 činy upřímného dávání: kompliment, pomoc, svůj čas, úsměv, povzbuzení. Všimni si, jak se TVOJE energie mění s každým činem.",
    m5L3Title: "Umění přijímat",
    m5L3Content: "Mnozí lidé umí dávat, ale neumí přijímat. Přijímání je také dar — pro dárce. Když s grácií přijmeš pomoc, lásku, kompliment nebo hojnost, uzavřeš kruh toku energie.",
    m5L3Exercise: "Dnes procvičuj plné přijímání. Když tě někdo pochválí, řekni 'Děkuji' bez vyhýbání. Když ti nabídne pomoc, přijmi ji. Všimni si svého odporu a nech ho změknout.",
    m5L4Title: "Budování smysluplných spojení",
    m5L4Content: "Nemáme kráčet sami. Kvalitní propojení znásobují tvou energii exponenciálně. Obklop se lidmi, kteří vidí tvé světlo a podporují tvůj růst. Buď tím člověkem pro ostatní.",
    m5L4Exercise: "Ozvi se někomu, s kým ses delší dobu nespojil. Sdílej něco upřímného. Zeptej se, jak se doopravdy má. Naslouchej hluboce.",
    m5L5Title: "Sdílej své světlo",
    m5L5Content: "Dokončil jsi pět sil. Rozumíš své identitě, zákonům, navigaci, rovnováze a síle propojení. Teď jdi — usměj se, zař a sdílej své světlo. Svět na tebe čeká.",
    m5L5Exercise: "Napiš dopis sobě od svého budoucího já — verze tebe, která žije s vysokou energií každý den. Co ti chce říct? Noš tento dopis u sebe.",

    // Common
    reflection: "Tvá reflexe",
    reflectionPlaceholder: "Zapiš své myšlenky, poznatky a objevy...",
    exercise: "Praktické cvičení",
    save: "Uložit",
    saved: "Uloženo!",
    next: "Další",
    previous: "Předchozí",
    complete: "Označit jako dokončené",
    
    // Progress
    overallProgress: "Celkový pokrok",
    modulesCompleted: "Dokončené moduly",
    lessonsCompleted: "Dokončené lekce",
    currentStreak: "Aktuální série",
    days: "dní",
    energyTrend: "Trend energie",
    yourJourney: "Tvoje cesta proměny",
    
    // Language
    language: "Jazyk",
    switchLang: "English",

    // Final Module
    fm_step1_title: "Teď nesbíráš informace.",
    fm_step1_subtitle: "Teď integruješ svůj život.",
    fm_step1_button: "Vstoupit do cesty",
    fm_step2_title: "Ohlédnutí",
    fm_step2_subtitle: "Co si odnáším z každého modulu?",
    fm_step2_takeaway: "Co si odnáším",
    fm_step2_practice: "Co žiju v praxi",
    fm_step3_title: "Tvůj život jako auto",
    fm_step3_subtitle: "Všechny části musí fungovat harmonicky",
    fm_step3_driver: "Řidič",
    fm_step3_gps: "GPS",
    fm_step3_fuel: "Palivo",
    fm_step3_passengers: "Spolucestující",
    fm_step3_q_driver: "Kdo opravdu jsem?",
    fm_step3_q_gps: "Kam mířím v životě?",
    fm_step3_q_fuel: "Co mě naplňuje energií?",
    fm_step3_q_passengers: "S kým chci cestovat životem?",
    fm_step4_title: "Tvůj akční plán",
    fm_step4_subtitle: "Postupné kroky k tvému novému životu",
    fm_step4_30days: "30 dní",
    fm_step4_90days: "90 dní",
    fm_step4_1year: "1 rok",
    fm_step5_title: "Tvůj vnitřní kompas",
    fm_step5_subtitle: "Vyber svých TOP 5 hodnot",
    fm_step5_family: "Rodina",
    fm_step5_health: "Zdraví",
    fm_step5_career: "Kariéra",
    fm_step5_friendship: "Přátelství",
    fm_step5_growth: "Duchovní růst",
    fm_step5_creativity: "Kreativita",
    fm_step5_freedom: "Svoboda",
    fm_step5_security: "Bezpečí",
    fm_step5_service: "Služba druhým",
    fm_step5_joy: "Zábava/radost",
    fm_step6_title: "Tvoje vize",
    fm_step6_subtitle: "Představ si svůj život",
    fm_step6_1year: "Za 1 rok",
    fm_step6_5years: "Za 5 let",
    fm_step6_legacy: "Můj odkaz",
    fm_step7_title: "Denní rituály",
    fm_step7_subtitle: "Ukotvení v každodenním životě",
    fm_step7_morning: "Ranní rituál",
    fm_step7_evening: "Večerní rituál",
    fm_step7_weekly: "Týdenní rituál",
    fm_step8_title: "Tvůj životní manifest",
    fm_step8_subtitle: "Tvé nové přesvědčení",
    fm_step9_title: "Kde jsi teď?",
    fm_step9_subtitle: "Reflexe tvého pokroku",
    fm_step9_identity: "Žiji podle své pravé identity",
    fm_step9_mindset: "Mám RICH mindset",
    fm_step9_energy: "Starám se o svou energii",
    fm_step9_relationships: "Mám harmonické vztahy",
    fm_step9_fulfillment: "Cítím se naplněný/á",
    fm_step10_title: "Překážky",
    fm_step10_subtitle: "Co tě může zastavit - a jak to překonat",
    fm_step10_time: "Nemám čas",
    fm_step10_hard: "Je to moc těžké",
    fm_step10_failed: "Zase jsem selhal/a",
    fm_step10_support: "Okolí mě nepodporuje",
    fm_step10_doubt: "Nevím, jestli to má smysl",
    fm_step11_title: "Iniciační rituál",
    fm_step11_subtitle: "Tvůj závazek k novému životu",
    fm_step11_name: "Tvé jméno",
    fm_step11_date: "Dnešní datum",
    fm_step11_signature: "Podpis",
    fm_issued: "ŘIDIČÁK NA ŽIVOT",
    fm_issued_subtitle: "VYDÁN",
    fm_final_message: "Teď už jen řiď. Svět potřebuje tvé světlo.",
    fm_continue: "Pokračovat",
    fm_back: "Zpět",
    fm_saving: "Ukládám...",
    }
    };

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => {
    return localStorage.getItem('app_language') || 'en';
  });

  const toggleLanguage = () => {
    const newLang = lang === 'en' ? 'cs' : 'en';
    setLang(newLang);
    localStorage.setItem('app_language', newLang);
  };

  const t = (key) => {
    return translations[lang]?.[key] || translations['en']?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}

export default LanguageContext;